name: Code Quality

on:  pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
      - run: pip install pytest pytest-cov poetry
      - run: |
          poetry config virtualenvs.create false
          poetry install --no-root
      - run: pytest ./tests/ --doctest-modules --junitxml=./reports/unit/junit.xml --cov=resgen --cov-report=xml:./reports/coverage/coverage.xml --cov-report=html
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit tests            # Name of the check run which will be created
          path: reports/unit/unit.xml  # Path to test results
          reporter: java-junit        # Format of test results
      - name: Coverage Reports
        uses: xportation/junit-coverage-report@main
        with:
          junit-path: ./reports/unit/unit.xml
          coverage-path: ./reports/coverage/coverage.xml