name: mkdocs-build

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install poetry
      - run: |
          poetry config virtualenvs.create false
          poetry install --only docs
      - run: mkdocs build --strict
