name: mkdocs-build

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - run: pip install poetry
      - run: |
          poetry config virtualenvs.create false
          poetry install --only docs
      - run: mkdocs build --strict
